apiVersion: v1
kind: Secret
metadata:
  name: vault
spec:
  template:
    spec:
      imagePullSecrets:
      - name: jfrog-registry-secret
      containers:
      - name: vault
        image: trial4w4crx.jfrog.io/vault-repo/vault-server:latest
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJjcmVkc1N0b3JlIjogImRlc2t0b3AuZXhlIgp9Cg==
